'build_storkmdm_apk':
  script:
  - git submodule update --init
  - source /home/gitlab-runner/.profile
  - echo $PATH
  - ls -la
  - git clone $CI_BUILD_REPO StorkMDM
  - cd StorkMDM
  - gradle clean build
  - cp app/build/outputs/apk/app-release*.apk /home/gitlab-runner
  - cd /home/gitlab-runner
  - rm -Rf StorkMDM
  - scp -i ~gitlab-runner/.ssh/pushgitlab app-release-*.apk teclib@vm000139.paas.teclib.infra:/srv/fdroid/repo
  - rm ~gitlab-runner/app-release-*.apk
  - ssh -i ~gitlab-runner/.ssh/executegitlab teclib@vm000139.paas.teclib.infra fdroid update -c
  tags:
  only:
  - tags
